---
title: "Itereation and List Columns"
output: github_document
---

```{r setting up R markdown}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lists 

You can put anything in a list 

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
  mat = matrix(1:8, nrow = 2, ncol = 4),
  summary = summary(rnorm(100))
)

l
```

```{r}
l$vec_numeric
l[[1]]
l[["vec_numeric"]]

l[["vec_numeric"]][1:3]
mean(l[["vec_numeric"]])
```

## For loop

Create new list 

```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = 0.2),
    d = rnorm(20, mean = -3, sd = 1)
  )
```

```{r}
list_norm
list_norm[[1]]
```

Pause and get our old function

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply this to each list element 

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])

```

Let's use a for loop

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  
}

```

## Let's try map

```{r}
output = map(list_norm, mean_and_sd)
```

what if you want different function

```{r}
output = map(list_norm, median)
```

Map variants 

```{r}
output = map_dbl(list_norm, median)
```

```{r}
output = map_df(list_norm, mean_and_sd, .id = "input")
```

## list columns 

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    sample = list_norm
  )
```

```{r}
listcol_df %>% pull(name)
listcol_df %>% pull(sample)

listcol_df %>% filter(name == "a")
```

Let's try some operations 

```{r}
mean_and_sd(listcol_df$sample[[1]])
mean_and_sd(listcol_df$sample[[2]])
mean_and_sd(listcol_df$sample[[3]])
```

Can I just map?

```{r}
map(listcol_df$sample, mean_and_sd)
```

Can I add a list column? Saving output in this dataframe

```{r}
listcol_df = 
  listcol_df %>% 
  mutate(
    summary = map(sample, mean_and_sd), 
    medians = map(sample, median)
    )
```

