---
title: "Writing Functions"
output: github_document
---

```{r setting up R markdown}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Do Something Simple 

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
#Z scores, SD away from the mean
```

I want a function to compute z scores 

```{r}
z_scores = function(x) {
  
  if(!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Inpute must have at least 3 numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x_vec)
```

Try function on other things 

```{r error = TRUE}
z_scores(3)
#Sd of 3 can't do
#can't do mean on character var 
z_scores(mtcars)
#can't take mena of dataset, only number list
z_scores(c(TRUE, TRUE, FALSE, TRUE))
#coerced to 0 and 1

```

